WITH FUNCTION GET_SIZE_BY_PAGES(NUM_OF_PAGE BIGINT, KB_MB_GB VARCHAR(2) DEFAULT 'KB') RETURN NUMBER(15, 2) AS
    V_SIZE_KB NUMBER(15, 2) := ROUND(PAGE() * NUM_OF_PAGE / 1024.00, 2);
BEGIN
    IF KB_MB_GB = 'MB' THEN
        RETURN V_SIZE_KB / 1024.00;
    ELSIF KB_MB_GB = 'GB' THEN
        RETURN V_SIZE_KB / 1024.00 / 1024.00;
    END IF;
    RETURN V_SIZE_KB;
END;
SELECT 
       T.OWNER,
       T.TABLE_NAME,
       GET_SIZE_BY_PAGES(INDEX_USED_PAGES(T.OWNER, T.INDEX_NAME), 'MB') AS TABLE_USED_SPACE_MB,
       GET_SIZE_BY_PAGES(INDEX_USED_PAGES(T.OWNER, T.INDEX_NAME), 'GB') AS TABLE_USED_SPACE_GB,
       TABLE_ROWCOUNT(T.OWNER, T.TABLE_NAME)                            AS TABLE_ROWCOUNT
FROM DBA_INDEXES T
WHERE T.OWNER IN ('LLSYOA') AND T.INDEX_TYPE='CLUSTER' and t.TABLE_NAME in (select table_name from dba_tables where owner='LLSYOA')
ORDER BY TABLE_USED_SPACE_MB DESC, TABLE_ROWCOUNT DESC;

